/*
 * Copyright (c) 2017. tangzx(love.tangzx@qq.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.tang.intellij.lua.project

import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.components.PersistentStateComponent
import com.intellij.openapi.components.State
import com.intellij.openapi.components.Storage
import com.intellij.util.xmlb.XmlSerializerUtil
import com.tang.intellij.lua.Constants
import com.tang.intellij.lua.lang.LuaLanguageLevel
import java.nio.charset.Charset

/**
 *
 * Created by tangzx on 2017/6/12.
 */
@State(name = "LuaSettings", storages = [(Storage("emmy.xml"))])
class LuaSettings : PersistentStateComponent<LuaSettings> {
    //自定义require函数，参考constructorNames
    var requireLikeFunctionNames: Array<String> = arrayOf("require")

    var constructorNames: Array<String> = arrayOf("new", "get")

    //Doc文档严格模式，对不合法的注解报错
    var isStrictDoc: Boolean = false

    //在未匹配end的statement后回车会自动补全
    var isSmartCloseEnd: Boolean = true

    //在代码完成时使用参数完成模板
    var autoInsertParameters: Boolean = false

    var isShowWordsInFile: Boolean = true

    // Throw errors if specified and found types do not match
    var isEnforceTypeSafety: Boolean = false

    var isNilStrict: Boolean = false

    var isRecognizeGlobalNameAsType = true

    var additionalSourcesRoot = arrayOf<String>()

    /**
     * 使用泛型
     */
    var enableGeneric: Boolean = false

    /**
     * 文件大小阈值 (KB)
     * UE 自动生成的文件可能很大，设置为 5MB 以支持大型 API 文件
     */
    var tooLargerFileThreshold = 5120

    var attachDebugDefaultCharsetName = "UTF-8"

    var attachDebugCaptureStd = true

    var attachDebugCaptureOutput = true

    /**
     * Lua language level
     */
    var languageLevel = LuaLanguageLevel.LUA53



    /**
     * Custom helper directory path
     * 自定义 helper 目录路径（包含自定义脚本的目录）
     */
    var customHelperPath = ""
    
    /**
     * Custom extension script name (without .lua extension)
     * 自定义扩展脚本名称（不含 .lua 后缀，如 "emmyHelper_custom"）
     * 如果为空，使用内置的 "emmyHelper_ue"
     */
    var customHelperExtName = ""

    /**
     * UE进程名称列表，用于调试器进程过滤
     */
    var ueProcessNames: Array<String> = arrayOf(
        "UnrealEngine", "UE4Editor", "UE5Editor", "UnrealEditor"
    )

    /**
     * 调试器进程黑名单，用于过滤不需要显示的系统进程
     */
    var debugProcessBlacklist: Array<String> = arrayOf(
        "winlogon", "csrss", "wininit", "services"
    )

    /**
     * 是否启用自定义文件模板
     */
    var enableCustomFileTemplate: Boolean = true

    /**
     * 自定义文件模板内容
     */
    var customFileTemplate: String = "---\n--- Generated by EmmyLua(https://github.com/EmmyLua)\n--- Created by \${USER}.\n--- DateTime: \${DATE} \${TIME}\n---\n\n---@class \${FILE_NAME}\nlocal \${FILE_NAME} = {}\n\nreturn \${FILE_NAME}"

    /**
     * 是否启用文件名替换功能
     */
    var enableFileNameReplacement: Boolean = true

    /**
     * 文件名替换占位符（默认为 ${FILE_NAME}）
     */
    var fileNamePlaceholder: String = "\${FILE_NAME}"

    /**
     * 开发模式：从项目源码目录自动读取 Lua 调试脚本
     * 启用后，emmyHelper.lua 等文件将从项目的 src/main/resources 目录读取，而非从插件 JAR 包中读取
     * 这样修改 Lua 脚本后无需重新打包插件即可生效
     * 
     * 开发模式会自动检测项目根目录下的 src/main/resources 目录
     */
    var enableDevMode: Boolean = false

    override fun getState(): LuaSettings {
        return this
    }

    override fun loadState(luaSettings: LuaSettings) {
        XmlSerializerUtil.copyBean(luaSettings, this)
    }

    var constructorNamesString: String
        get() {
            return constructorNames.joinToString(";")
        }
        set(value) {
            constructorNames = value.split(";").map { it.trim() }.toTypedArray()
        }

    val attachDebugDefaultCharset: Charset get() {
        return Charset.forName(attachDebugDefaultCharsetName) ?: Charset.forName("UTF-8")
    }
    var requireLikeFunctionNamesString: String
        get() {
            return requireLikeFunctionNames.joinToString(";")
        }
        set(value) {
            requireLikeFunctionNames = value.split(";").toTypedArray()
        }

    var ueProcessNamesString: String
        get() {
            return ueProcessNames.joinToString(";")
        }
        set(value) {
            ueProcessNames = value.split(";").filter { it.isNotBlank() }.toTypedArray()
        }

    var debugProcessBlacklistString: String
        get() {
            return debugProcessBlacklist.joinToString(";")
        }
        set(value) {
            debugProcessBlacklist = value.split(";").filter { it.isNotBlank() }.toTypedArray()
        }

    companion object {

        val instance: LuaSettings
            get() = ApplicationManager.getApplication().getService(LuaSettings::class.java)

        fun isConstructorName(name: String): Boolean {
            return instance.constructorNames.contains(name)
        }

        fun isRequireLikeFunctionName(name: String): Boolean {
            return instance.requireLikeFunctionNames.contains(name) || name == Constants.WORD_REQUIRE
        }
    }
}
