# GitHub Actions 工作流名称
name: Build and Release on Push to Main

# 触发工作流的事件
on:
  push:
    branches:
      - main # 当 main 分支有新的推送时触发

# 工作流运行的任务
jobs:
  build-and-release:
    # 使用最新的 Ubuntu 虚拟机环境
    runs-on: ubuntu-latest
    # 赋予工作流写入 Releases 的权限
    permissions:
      contents: write

    steps:
      # 第一步：检出代码
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 第二步：设置 Java 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 第三步：设置 Gradle 环境
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # 第四步：执行 Gradle 打包命令
      - name: Build with Gradle
        run: ./gradlew buildPlugin -x buildSearchableOptions

      # 第五步：生成 Release 的更新日志 (Release Body)
      # <--- 修正点：增加对空 commit 日志的判断，使工作流更健壮
      - name: Generate release notes
        id: generate_notes
        run: |
          # 1. 将 git log 的结果存入一个变量
          LOG_CONTENT=$(git log ${{ github.event.before }}..${{ github.event.after }} --pretty=format:'* %s (%h)')

          # 2. 检查变量是否为空
          if [ -z "$LOG_CONTENT" ]; then
            # 3. 如果为空，则设置一个默认的提示信息
            LOG_CONTENT="* 本次推送没有包含新的代码提交。"
          fi
          
          # 4. 使用多行语法将保证非空的变量写入 GITHUB_OUTPUT
          {
            echo 'changelog<<EOF'
            echo "$LOG_CONTENT"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
      
      # 第六步：设置发布信息
      - name: Set Release Info
        id: set_release_info
        run: echo "RELEASE_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      # 第七步：创建 GitHub Release 并上传构建产物
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          body: |
            ## 自动构建产物

            **✨ 本次更新包含以下提交:**
            ${{ steps.generate_notes.outputs.changelog }}
          
          tag_name: release-${{ env.RELEASE_DATE }}-${{ github.sha }}
          name: Auto Build - ${{ env.RELEASE_DATE }}
          prerelease: true
          files: build/distributions/*.zip
